In [1]:
import numpy as np

In [2]:
def get_board_lines(board: np.ndarray):
    rows = [row for row in board]  # 所有行
    cols = [board[:, i] for i in range(board.shape[1])]  # 所有列
    
    # 所有斜对角（左上到右下）
    diags = [board.diagonal(i) for i in range(-board.shape[0]+1, board.shape[1])]
    
    # 所有反斜对角（右上到左下）
    anti_diags = [np.fliplr(board).diagonal(i) 
                for i in range(-board.shape[0]+1, board.shape[1])]
    return rows + cols + diags + anti_diags

In [3]:
a = np.arange(12).reshape(3, 4)
lines = ["".join(x.astype(str)) for x in get_board_lines(a)]

print(a)
print(lines)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
['0123', '4567', '891011', '048', '159', '2610', '3711', '8', '49', '0510', '1611', '27', '3', '11', '710', '369', '258', '14', '0']


In [10]:
import re
from enum import IntEnum

class BoardPattern(IntEnum):
    FIVE = 1
    OPEN_FOUR = 2
    BLOCKED_FOUR = 3
    OPEN_THREE = 4
    BLOCKED_THREE = 5
    OPEN_TWO = 6

def pattern2str(pattern: IntEnum):
    dic = {
        1:"FIVE",
        2:"OPEN_FOUR",
        3:"BLOCKED_FOUR",
        4:"OPEN_THREE",
        5:"BLOCKED_THREE",
        6:"OPEN_TWO"
    }
    return dic[pattern]

board_patterns = {
    BoardPattern.FIVE: ["11111"],
    BoardPattern.OPEN_FOUR: ["011110"],  # 活四：己方下一手必成五连
    BoardPattern.BLOCKED_FOUR: [
        "01111(2|$)",
        "(2|^)11110",
        "0101110",
        "0110110",
        "0111010",
    ],  # 冲四的定义是：己方下一步可形成五连，但对手也只需一步可以立即阻止五连形成
    BoardPattern.OPEN_THREE: ["01110", "010110", "011010"],
    BoardPattern.BLOCKED_THREE: ["(2|^)1110", "0111(2|$)", "(2|^)10110", "1101(2|$)"],
    BoardPattern.OPEN_TWO: ["0110"],
}
scores = {
    BoardPattern.FIVE: 1e9,
    BoardPattern.OPEN_FOUR: 10000,
    BoardPattern.BLOCKED_FOUR: 1000,
    BoardPattern.OPEN_THREE: 1000,
    BoardPattern.BLOCKED_THREE: 100,
    BoardPattern.OPEN_TWO: 100,
}

In [18]:
state = "1110"

game_score = 0
for pattern, regexs in board_patterns.items():
    for regex in regexs:
        if re.search(regex, state):
            game_score += scores[pattern]
            print(f"pattern {pattern2str(pattern)} match!")

pattern BLOCKED_THREE match!
